# version: '3.8'

# services:
#   nestjs-app-docker:
#     build: .
#     container_name: nestjs_api_devops
#     restart: always
#     ports:
#       - "6969:5000" # Map port 3001 của máy ảo vào port 5000 của container
#     env_file:
#       - .env
#     environment:
#       - NODE_ENV=production
#       # Quan trọng: Ghi đè DATABASE_HOST để trỏ về IP máy ảo (vì DB đang nằm ngoài Docker)
#       # - DATABASE_HOST=pg-3a624ae7-dqv4work-6f03.h.aivencloud.com
#     networks:
#       - nestjs_network

# networks:
#   nestjs_network:
#     driver: bridge



version: '3.8'

services:
  nestjs-app-docker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api_devops
    restart: always
    ports:
      - "6969:5000" 
    env_file:
      - .env  # Docker sẽ tự nạp DATABASE_HOST, SSL_ENABLED... từ đây
    environment:
      - NODE_ENV=production
    networks:
      - nestjs_network
    logging:
      driver: loki
      options:
        loki-url: "http://171.244.62.122:5003/loki/api/v1/push"



networks:
  nestjs_network:
    driver: bridge