name: CI/CD với Docker Hub

on:
  push:
    branches: [main] # Chạy khi bạn push vào branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Thay 'vinh' bằng username Docker Hub của bạn
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-api:latest

  deploy-to-server:
    needs: build-and-push # Đợi build xong mới deploy
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Truy cập vào thư mục dự án trên server
            cd ~/projects-docker/nestjs-devops

            # Login Docker trên server (chỉ cần thiết nếu repo là private)
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Kéo bản mới nhất về và khởi động lại
            docker-compose pull
            docker-compose up -d

            # Dọn dẹp các image cũ để tiết kiệm ổ cứng
            docker image prune -f
